firmware_requirements:
  NX_Firmware: "20.2.0"
  Atmosphere: "20.2.0"
  hekate: "20.2.0"
  Lockpick_RCMaster: "20.2.0"
  TegraExplorer: "17.0.0"
  dbi: "20.2.0"
  Goldleaf: "20.2.0"
  Awoo-Installer: "15.0.1"
  JKSV: "20.2.0"
  nxdumptool: "20.2.0"
  aio-switch-updater: "17.0.0"
  MissionControl: "20.2.0"
  nx-ovlloader: "20.2.0"
  SwitchThemeInjector: "20.2.0"
  incognito_rcm: "16.0.0"
  AtmoPackVanilla: "20.2.0"
  nso-icon-tool: "20.2.0"
  sys-screenuploader: "20.2.0"
  sphaira: "20.2.0"
  Moonlight-Switch: "20.2.0"
  uLaunch: "20.2.0"
  switch_AIO_LS_pack: "20.2.0"
  switchfin: "20.2.0"
  SaltyNX: "20.2.0"
  FPSLocker: "20.2.0"
  SwitchLayoutEditor: "20.2.0"
  sys-tune: "20.2.0"
  sudachi.emuplace.app: "20.2.0"
  SysDVR: "20.2.0"
  dvr-patches: "20.1.0"
  DeepSea: "19.0.0"
  NxFileViewer: "20.2.0"
  sys-con: "20.2.0"
  ftpsrv: "20.2.0"
  jfsw-switch: "20.2.0"
  NooDS: "20.2.0"
  ftpd: "20.2.0"
  Rekado: "20.2.0"
  SwitchWave: "20.2.0"
  EdiZon-Overlay: "20.2.0"
  NX-Activity-Log: "20.2.0"
  Switch-Firmware-Dumper: "20.2.0"
  sys-botbase: "19.0.0"
  sys-clk: "19.0.0"
  nxboot: "20.2.0"
  Tinwoo-Release: "20.2.0"
  Status-Monitor-Overlay: "20.2.0"
  NX-Venom: "20.2.0"
  Lakka-LibreELEC: "20.2.0"
  RetroArch: "20.2.0"
  flycast: "20.2.0"
  SimpleModDownloader: "20.2.0"
  AtmoPackUpdater: "20.2.0"
  Ls-News: "15.0.0"
  Ultimate-Switch-Hack-Script: "20.2.0"
  PKHeX: "20.2.0"
  nsz: "20.2.0"
  Haku33: "20.2.0"
  The-Simpsons-Hit-and-Run: "20.2.0"
  switch-ezremote-client: "20.2.0"
  nxmp: "20.2.0"
  deltarune_fr_switch: "20.2.0"

# Default firmware version for unknown projects
default_firmware: "20.2.0" 