projects:
  - repo: "THZoria/NX_Firmware"
  - repo: "Atmosphere-NX/Atmosphere"
  - repo: "CTCaer/hekate"
  - repo: "THZoria/Lockpick_RCMaster"
  - repo: "suchmememanyskill/TegraExplorer"
  - repo: "rashevskyv/dbi"
  - repo: "XorTroll/Goldleaf"
  - repo: "Huntereb/Awoo-Installer"
  - repo: "J-D-K/JKSV"
  - repo: "DarkMatterCore/nxdumptool"
  - repo: "HamletDuFromage/aio-switch-updater"
  - repo: "ndeadly/MissionControl"
  - repo: "WerWolv/nx-ovlloader"
  - repo: "exelix11/SwitchThemeInjector"
  - repo: "jimzrt/incognito_rcm"
  - repo: "THZoria/AtmoPackVanilla"
  - repo: "dslatt/nso-icon-tool"
  - repo: "bakatrouble/sys-screenuploader"
  - repo: "ITotalJustice/sphaira"
  - repo: "XITRIX/Moonlight-Switch"
  - repo: "XorTroll/uLaunch"
  - repo: "shadow2560/switch_AIO_LS_pack"
  - repo: "dragonflylee/switchfin"
  - repo: "masagrator/SaltyNX"
  - repo: "masagrator/FPSLocker"
  - repo: "FuryBaguette/SwitchLayoutEditor"
  - repo: "TheReconJacob/sys-tune"
  - repo: "emuplace/sudachi.emuplace.app"
  - repo: "exelix11/SysDVR"
  - repo: "exelix11/dvr-patches"
  - repo: "Team-Neptune/DeepSea"
  - repo: "Myster-Tee/NxFileViewer"
  - repo: "o0Zz/sys-con"
  - repo: "ITotalJustice/ftpsrv"
  - repo: "alexart878/jfsw-switch"
  - repo: "Hydr8gon/NooDS"
  - repo: "mtheall/ftpd"
  - repo: "MenosGrante/Rekado"
  - repo: "averne/SwitchWave"
  - repo: "proferabg/EdiZon-Overlay"
  - repo: "zdm65477730/NX-Activity-Log"
  - repo: "mrdude2478/Switch-Firmware-Dumper"
  - repo: "olliz0r/sys-botbase"
  - repo: "retronx-team/sys-clk"
  - repo: "mologie/nxboot"
  - repo: "mrdude2478/Tinwoo-Release"
  - repo: "masagrator/Status-Monitor-Overlay"
  - repo: "CatcherITGF/NX-Venom"
  - repo: "libretro/Lakka-LibreELEC"
  - repo: "libretro/RetroArch"
  - repo: "flyinghead/flycast"
  - repo: "PoloNX/SimpleModDownloader"
  - repo: "PoloNX/AtmoPackUpdater"
  - repo: "PoloNX/Ls-News"
  - repo: "shadow2560/Ultimate-Switch-Hack-Script"
  - repo: "kwsch/PKHeX"
  - repo: "nicoboss/nsz"
  - repo: "StarDustCFW/Haku33"
  - repo: "ZenoArrows/The-Simpsons-Hit-and-Run"
  - repo: "cy33hc/switch-ezremote-client"
  - repo: "proconsule/nxmp"
  - repo: "THZoria/deltarune_fr_switch" 